In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
df = pd.read_csv("../Dataset/smart_pharmacy_dataset.csv")

df.head()

,medicine_id,medicine_name,category,year,week_number,season,current_stock,previous_week_sales,sales_last_2_week,sales_last_4_week_average,flu_cases,dengue_cases,covid_cases,supplier_delivery_days,stock_received,expiry_risk,is_holiday_week,medicine_importance,next_week_demand
0,MED001,Paracetamol,Fever/Pain Relief,2023,1,Winter,1137,355,355,355.00,376,19,42,12,381,12,1,High,311
1,MED001,Paracetamol,Fever/Pain Relief,2023,2,Winter,12,355,291,355.00,432,23,27,9,413,9,0,High,311
2,MED001,Paracetamol,Fever/Pain Relief,2023,3,Winter,26,291,355,323.00,362,12,11,11,387,18,0,High,251
3,MED001,Paracetamol,Fever/Pain Relief,2023,4,Winter,641,248,291,298.00,302,14,61,14,331,0,0,High,266
4,MED001,Paracetamol,Fever/Pain Relief,2023,5,Winter,407,257,248,287.75,321,20,104,10,427,11,0,High,258

In [20]:
df = df.sort_values(
    by=["year", "week_number", "medicine_id"]
)

df.head()

,medicine_id,medicine_name,category,year,week_number,season,current_stock,previous_week_sales,sales_last_2_week,sales_last_4_week_average,flu_cases,dengue_cases,covid_cases,supplier_delivery_days,stock_received,expiry_risk,is_holiday_week,medicine_importance,next_week_demand
0,MED001,Paracetamol,Fever/Pain Relief,2023,1,Winter,1137,355,355,355.0,376,19,42,12,381,12,1,High,311
156,MED002,Ibuprofen,Fever/Pain Relief,2023,1,Winter,635,234,234,234.0,296,22,36,8,383,25,1,High,177
312,MED003,Aspirin,Fever/Pain Relief,2023,1,Winter,420,267,267,267.0,333,23,52,12,373,12,1,High,219
468,MED004,Diclofenac,Fever/Pain Relief,2023,1,Winter,237,95,95,95.0,398,17,30,10,150,11,1,Medium,104
624,MED005,Naproxen,Fever/Pain Relief,2023,1,Winter,225,89,89,89.0,297,19,0,13,120,0,1,Medium,89

In [21]:
df.shape

(23400, 19)

In [22]:
df.columns

Index(['medicine_id', 'medicine_name', 'category', 'year', 'week_number',
       'season', 'current_stock', 'previous_week_sales', 'sales_last_2_week',
       'sales_last_4_week_average', 'flu_cases', 'dengue_cases', 'covid_cases',
       'supplier_delivery_days', 'stock_received', 'expiry_risk',
       'is_holiday_week', 'medicine_importance', 'next_week_demand'],
      dtype='str')

In [23]:
df.info()

<class 'pandas.DataFrame'>
Index: 23400 entries, 0 to 23399
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   medicine_id                23400 non-null  str
 1   medicine_name              23400 non-null  str
 2   category                   23400 non-null  str
 3   year                       23400 non-null  int64
 4   week_number                23400 non-null  int64
 5   season                     23400 non-null  str
 6   current_stock              23400 non-null  int64
 7   previous_week_sales        23400 non-null  int64
 8   sales_last_2_week          23400 non-null  int64
 9   sales_last_4_week_average  23400 non-null  float64
 10  flu_cases                  23400 non-null  int64
 11  dengue_cases               23400 non-null  int64
 12  covid_cases                23400 non-null  int64
 13  supplier_delivery_days     23400 non-null  int64
 14  stock_received             23400 non-null  int64
 15  expiry_risk                23400 non-null  int64
 16  is_holiday_week            23400 non-null  int64
 17  medicine_importance        23400 non-null  str
 18  next_week_demand           23400 non-null  int64
dtypes: float64(1), int64(13), str(5)
memory usage: 3.6 MB

In [24]:
df.isnull().sum()

medicine_id                  0
medicine_name                0
category                     0
year                         0
week_number                  0
season                       0
current_stock                0
previous_week_sales          0
sales_last_2_week            0
sales_last_4_week_average    0
flu_cases                    0
dengue_cases                 0
covid_cases                  0
supplier_delivery_days       0
stock_received               0
expiry_risk                  0
is_holiday_week              0
medicine_importance          0
next_week_demand             0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df["medicine_id"].nunique() # medicine count

150

In [27]:
df.groupby("medicine_id")["week_number"].count()

medicine_id
MED001    156
MED002    156
MED003    156
MED004    156
MED005    156
         ...
MED146    156
MED147    156
MED148    156
MED149    156
MED150    156
Name: week_number, Length: 150, dtype: int64

In [28]:
df.describe()

,year,week_number,current_stock,previous_week_sales,sales_last_2_week,sales_last_4_week_average,flu_cases,dengue_cases,covid_cases,supplier_delivery_days,stock_received,expiry_risk,is_holiday_week,next_week_demand
count,23400.000000,23400.000000,23400.000000,23400.000000,23400.000000,23400.000000,23400.000000,23400.000000,23400.000000,23400.000000,23400.000000,23400.000000,23400.000000,23400.000000
mean,2024.000000,26.500000,109.840214,55.427564,55.433034,55.458846,159.884316,98.613333,43.532393,5.603162,80.690385,15.150812,0.134615,54.039829
std,0.816514,15.008652,101.593684,41.061300,41.074837,39.784539,127.159569,110.002520,35.814817,3.135179,59.970865,10.784963,0.341320,39.753799
min,2023.000000,1.000000,1.000000,7.000000,7.000000,8.000000,23.000000,5.000000,0.000000,2.000000,11.000000,0.000000,0.000000,6.000000
25%,2023.000000,13.750000,48.000000,29.000000,29.000000,29.500000,64.000000,24.000000,17.000000,3.000000,42.000000,6.000000,0.000000,28.000000
50%,2024.000000,26.500000,82.000000,44.000000,44.000000,44.000000,99.000000,46.000000,35.000000,5.000000,63.000000,15.000000,0.000000,43.000000
75%,2025.000000,39.250000,139.000000,69.000000,69.000000,69.250000,293.000000,100.250000,59.000000,7.000000,101.000000,22.000000,0.000000,68.000000
max,2025.000000,52.000000,1377.000000,435.000000,435.000000,360.750000,545.000000,467.000000,171.000000,15.000000,660.000000,61.000000,1.000000,445.000000